MobyDickMVC/Models/wordsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MobyDickMVC.Models
{
    public class wordsModel
    {
        public string text { get; set; }
        public string count { get; set; }
    }
}

MobyDickMVC/Controllers/WordController.cs
using MobyDickMVC.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace MobyDickMVC.Controllers
{
    public class WordController : Controller
    {
        // GET: Word
        public ActionResult list()
        {
            var data = new List<wordsModel>();
            data = ReturnData();

            return View(data);
        }

        public List<wordsModel> ReturnData()
        {
            XElement root = XElement.Load(Server.MapPath("~/XML/MobyDick.xml"));
            var xml = root.Elements("word")
                                  .OrderByDescending(s => (int)s.Attribute("count"))
                                  .ToArray();
            root.RemoveAll();
            foreach (XElement tab in xml)
                root.Add(tab);
            root.Save(Server.MapPath("~/XML/MobyDick2.xml"));
            string xmldata = Server.MapPath("~/XML/MobyDick2.xml");
            DataSet ds = new DataSet();
            ds.ReadXml(xmldata);
            var wordlist = new List<wordsModel>();
            wordlist = (from rows in ds.Tables[0].AsEnumerable()
                        select new wordsModel
                        {
                            text = rows[0].ToString(),
                            count = rows[1].ToString()
                        }).Take(10).ToList();

            return wordlist;
        }
    }
}

MobyDickMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("List", "Word", "Word/list", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MobyDickMVC/Views/Word/list.cshtml
@model IEnumerable<MobyDickMVC.Models.wordsModel>

@{
    ViewBag.Title = "List";
}

<h2>Top 10 words of Moby Dick</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.count)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.count)
        </td>
    </tr>
}

</table>